2025-03-02 03:53:25,969 - trakademik - INFO - Application started
2025-03-02 03:53:26,186 - trakademik - INFO - Request started | 484992fa-8271-449c-bf05-4335aad9e9c3 | GET /
2025-03-02 03:53:26,192 - trakademik - INFO - Request completed | 484992fa-8271-449c-bf05-4335aad9e9c3 | Status: 200 | Time: 0.004s
2025-03-02 03:53:26,377 - trakademik - INFO - Request started | 0fe18209-4a67-42f9-ab57-6c26a6e28045 | GET /favicon.ico
2025-03-02 03:53:26,379 - trakademik - INFO - Request completed | 0fe18209-4a67-42f9-ab57-6c26a6e28045 | Status: 404 | Time: 0.001s
2025-03-02 03:53:32,602 - trakademik - INFO - Request started | 9218d3f1-efdd-444f-ba0b-e45f2451e551 | GET /docs
2025-03-02 03:53:32,605 - trakademik - INFO - Request completed | 9218d3f1-efdd-444f-ba0b-e45f2451e551 | Status: 200 | Time: 0.001s
2025-03-02 03:53:33,055 - trakademik - INFO - Request started | 80ee586b-430c-4092-a02e-5da224cafbcc | GET /openapi.json
2025-03-02 03:53:33,107 - trakademik - INFO - Request completed | 80ee586b-430c-4092-a02e-5da224cafbcc | Status: 200 | Time: 0.052s
2025-03-02 03:53:49,498 - trakademik - INFO - Request started | a0ed31c1-ed03-42f3-87b3-d4b10653ce46 | POST /api/v1/staff/departments/
2025-03-02 03:53:49,499 - trakademik - INFO - Request completed | a0ed31c1-ed03-42f3-87b3-d4b10653ce46 | Status: 422 | Time: 0.001s
2025-03-02 03:54:05,321 - trakademik - INFO - Request started | 889a023e-de24-414d-8ac2-c52387e494d7 | POST /api/v1/staff/departments/
2025-03-02 03:54:05,323 - trakademik - INFO - Request completed | 889a023e-de24-414d-8ac2-c52387e494d7 | Status: 422 | Time: 0.002s
2025-03-02 03:54:18,853 - trakademik - INFO - Request started | 119a75d8-0965-418c-ad39-355c2c2df702 | GET /docs
2025-03-02 03:54:18,854 - trakademik - INFO - Request completed | 119a75d8-0965-418c-ad39-355c2c2df702 | Status: 200 | Time: 0.001s
2025-03-02 03:54:19,043 - trakademik - INFO - Request started | fec23fb7-eac1-41bd-83dd-c5543876b404 | GET /openapi.json
2025-03-02 03:54:19,044 - trakademik - INFO - Request completed | fec23fb7-eac1-41bd-83dd-c5543876b404 | Status: 200 | Time: 0.001s
2025-03-02 03:54:46,563 - trakademik - INFO - Application started
2025-03-02 03:54:51,563 - trakademik - INFO - Request started | 62ef9b31-637d-4ac8-a1f5-7a894705e3e1 | GET /
2025-03-02 03:54:51,566 - trakademik - INFO - Request completed | 62ef9b31-637d-4ac8-a1f5-7a894705e3e1 | Status: 200 | Time: 0.001s
2025-03-02 03:54:51,827 - trakademik - INFO - Request started | 7c385df8-6c98-40d2-834a-cbce5b728d8c | GET /favicon.ico
2025-03-02 03:54:51,828 - trakademik - INFO - Request completed | 7c385df8-6c98-40d2-834a-cbce5b728d8c | Status: 404 | Time: 0.000s
2025-03-02 03:54:57,862 - trakademik - INFO - Request started | 1b7b10d3-c45c-4d29-b83d-666f51d8bbb0 | GET /docs
2025-03-02 03:54:57,862 - trakademik - INFO - Request completed | 1b7b10d3-c45c-4d29-b83d-666f51d8bbb0 | Status: 200 | Time: 0.000s
2025-03-02 03:54:58,020 - trakademik - INFO - Request started | 4dec7783-b4a1-4f54-a10e-f2e29071e7c7 | GET /openapi.json
2025-03-02 03:54:58,061 - trakademik - INFO - Request completed | 4dec7783-b4a1-4f54-a10e-f2e29071e7c7 | Status: 200 | Time: 0.040s
2025-03-02 03:55:08,569 - trakademik - INFO - Request started | d6c26db7-e7ca-4f8f-8317-793d64c88c58 | POST /api/v1/staff/departments/
2025-03-02 03:55:08,576 - trakademik - ERROR - Unhandled exception | d6c26db7-e7ca-4f8f-8317-793d64c88c58 | 
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\middleware\error_handler.py", line 36, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 153, in call_next
    raise app_exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\routers\staff_organization\staff_departments.py", line 25, in create_staff_department
    return staff_departments_crud.create_department(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\crud\staff_organization\staff_departments.py", line 30, in create_department
    department = self.factory.create_staff_department(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\factories\staff_departments.py", line 32, in create_staff_department
    name=self.validator.validate_name(new_department.name),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\validators.py", line 16, in validate_name
    raise TextTooShortError(input = value)
app.services.errors.staff_organisation_errors.TextTooShortError
2025-03-02 03:55:08,859 - trakademik - WARNING - TextTooShortError | d6c26db7-e7ca-4f8f-8317-793d64c88c58 | Entity creation attempted with short name : s
2025-03-02 05:26:11,052 - trakademik - INFO - Application started
2025-03-02 05:33:49,725 - trakademik - INFO - Request started | d6274be5-9b02-48d0-9258-0e375a390085 | GET /
2025-03-02 05:33:49,739 - trakademik - INFO - Request completed | d6274be5-9b02-48d0-9258-0e375a390085 | Status: 200 | Time: 0.003s
2025-03-02 05:33:50,056 - trakademik - INFO - Request started | cef5e1be-8ab4-4532-b4fa-a3b19b382b0c | GET /favicon.ico
2025-03-02 05:33:50,058 - trakademik - INFO - Request completed | cef5e1be-8ab4-4532-b4fa-a3b19b382b0c | Status: 404 | Time: 0.002s
2025-03-02 05:33:53,654 - trakademik - INFO - Request started | 86a831b8-3024-4497-a3c6-4f05997d1b36 | GET /docs
2025-03-02 05:33:53,656 - trakademik - INFO - Request completed | 86a831b8-3024-4497-a3c6-4f05997d1b36 | Status: 200 | Time: 0.000s
2025-03-02 05:33:53,843 - trakademik - INFO - Request started | 9a195038-b450-410f-917d-787a840895a6 | GET /openapi.json
2025-03-02 05:33:53,898 - trakademik - INFO - Request completed | 9a195038-b450-410f-917d-787a840895a6 | Status: 200 | Time: 0.055s
2025-03-02 05:34:17,076 - trakademik - INFO - Request started | 0b65b710-2209-4daa-b644-a0e841c3324d | POST /api/v1/staff/departments/
2025-03-02 05:34:17,094 - trakademik - ERROR - Unhandled exception | 0b65b710-2209-4daa-b644-a0e841c3324d | 
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\middleware\error_handler.py", line 36, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 153, in call_next
    raise app_exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\routers\staff_organization\staff_departments.py", line 25, in create_staff_department
    return staff_departments_crud.create_department(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\crud\staff_organization\staff_departments.py", line 30, in create_department
    department = self.factory.create_staff_department(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\factories\staff_departments.py", line 32, in create_staff_department
    name=self.validator.validate_name(new_department.name),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\validators.py", line 16, in validate_name
    raise TextTooShortError(input = value)
app.services.errors.staff_organisation_errors.TextTooShortError
2025-03-02 05:34:17,257 - trakademik - WARNING - TextTooShortError | 0b65b710-2209-4daa-b644-a0e841c3324d | Entity creation attempted with short name : A
2025-03-02 05:48:16,300 - trakademik - INFO - Request started | ae7c77af-9e54-415f-8fd2-be7dd58509f1 | GET /docs
2025-03-02 05:48:16,301 - trakademik - INFO - Request completed | ae7c77af-9e54-415f-8fd2-be7dd58509f1 | Status: 200 | Time: 0.001s
2025-03-02 05:48:16,503 - trakademik - INFO - Request started | 8bd701eb-21c7-45da-8478-f61638f458f2 | GET /openapi.json
2025-03-02 05:48:16,506 - trakademik - INFO - Request completed | 8bd701eb-21c7-45da-8478-f61638f458f2 | Status: 200 | Time: 0.002s
2025-03-02 05:48:37,869 - trakademik - INFO - Request started | d61258e6-6cb6-4a68-a2af-ae6dbede1302 | POST /api/v1/staff/departments/
2025-03-02 05:48:37,872 - trakademik - ERROR - Unhandled exception | d61258e6-6cb6-4a68-a2af-ae6dbede1302 | 
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\middleware\error_handler.py", line 36, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 153, in call_next
    raise app_exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\routers\staff_organization\staff_departments.py", line 25, in create_staff_department
    return staff_departments_crud.create_department(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\crud\staff_organization\staff_departments.py", line 30, in create_department
    department = self.factory.create_staff_department(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\factories\staff_departments.py", line 32, in create_staff_department
    name=self.validator.validate_name(new_department.name),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\validators.py", line 12, in validate_name
    raise EmptyFieldError(input = value)
app.services.errors.staff_organisation_errors.EmptyFieldError
2025-03-02 05:48:37,878 - trakademik - WARNING - EmptyFieldError | d61258e6-6cb6-4a68-a2af-ae6dbede1302 | Entity creation attempted without name : 
2025-03-02 05:58:45,848 - trakademik - INFO - Application started
2025-03-02 05:59:58,266 - trakademik - INFO - Application started
2025-03-02 06:00:04,077 - trakademik - INFO - Request started | 73ed831f-fdbe-435e-a6ee-48b9faee04dd | GET /docs
2025-03-02 06:00:04,085 - trakademik - INFO - Request completed | 73ed831f-fdbe-435e-a6ee-48b9faee04dd | Status: 200 | Time: 0.001s
2025-03-02 06:00:04,223 - trakademik - INFO - Request started | 410234be-3e05-42c0-b16e-30f9cb983e91 | GET /openapi.json
2025-03-02 06:00:04,259 - trakademik - INFO - Request completed | 410234be-3e05-42c0-b16e-30f9cb983e91 | Status: 200 | Time: 0.033s
2025-03-02 06:05:08,348 - trakademik - INFO - Application started
2025-03-02 06:15:03,048 - trakademik - INFO - Application started
2025-03-02 06:16:07,160 - trakademik - INFO - Request started | 7d49d0e0-e079-479c-ba4e-728bada9918e | POST /api/v1/staff/departments/
2025-03-02 06:16:07,168 - trakademik - ERROR - Unhandled exception | 7d49d0e0-e079-479c-ba4e-728bada9918e | 
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\middleware\error_handler.py", line 36, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 153, in call_next
    raise app_exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\routers\staff_organization\staff_departments.py", line 25, in create_staff_department
    return staff_departments_crud.create_department(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\crud\staff_organization\staff_departments.py", line 30, in create_department
    department = self.factory.create_staff_department(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\factories\staff_departments.py", line 32, in create_staff_department
    name=self.validator.validate_name(new_department.name),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\validators.py", line 16, in validate_name
    raise TextTooShortError(input = value)
app.services.errors.staff_organisation_errors.TextTooShortError
2025-03-02 06:17:03,989 - trakademik - INFO - Application started
2025-03-02 06:17:11,112 - trakademik - INFO - Request started | c28ccd2b-6bcd-4915-9cb0-b8cc9a4fae1f | GET /docs
2025-03-02 06:17:11,113 - trakademik - INFO - Request completed | c28ccd2b-6bcd-4915-9cb0-b8cc9a4fae1f | Status: 200 | Time: 0.000s
2025-03-02 06:17:11,272 - trakademik - INFO - Request started | bbced75b-15bc-4294-80ba-fe65267b28b8 | GET /openapi.json
2025-03-02 06:17:11,325 - trakademik - INFO - Request completed | bbced75b-15bc-4294-80ba-fe65267b28b8 | Status: 200 | Time: 0.052s
2025-03-02 06:17:23,785 - trakademik - INFO - Request started | 06698723-e1e3-41e2-9a9e-8d077e18b79a | POST /api/v1/staff/departments/
2025-03-02 06:17:23,790 - trakademik - ERROR - Unhandled exception | 06698723-e1e3-41e2-9a9e-8d077e18b79a | 
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\middleware\error_handler.py", line 36, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 153, in call_next
    raise app_exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\routers\staff_organization\staff_departments.py", line 25, in create_staff_department
    return staff_departments_crud.create_department(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\crud\staff_organization\staff_departments.py", line 30, in create_department
    department = self.factory.create_staff_department(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\factories\staff_departments.py", line 32, in create_staff_department
    name=self.validator.validate_name(new_department.name),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\Desktop\Engineering\Projects\TraKademik\V2\app\services\staff_organization\validators.py", line 16, in validate_name
    raise TextTooShortError(input = value)
app.services.errors.staff_organisation_errors.TextTooShortError
2025-03-02 06:17:23,804 - trakademik - WARNING - TextTooShortError | 06698723-e1e3-41e2-9a9e-8d077e18b79a | Entity creation attempted with short name : h
2025-03-02 07:19:28,495 - trakademik - INFO - Application started
2025-03-02 20:46:32,555 - trakademik - INFO - Application started
2025-03-02 20:46:34,214 - trakademik - INFO - Request started | 242bf6a3-3405-407d-87e9-32acaf26e2e7 | GET /
2025-03-02 20:46:34,216 - trakademik - INFO - Request completed | 242bf6a3-3405-407d-87e9-32acaf26e2e7 | Status: 200 | Time: 0.002s
2025-03-02 20:46:34,436 - trakademik - INFO - Request started | 524f8894-37cf-4d02-859f-2ae0ccf762d3 | GET /favicon.ico
2025-03-02 20:46:34,439 - trakademik - INFO - Request completed | 524f8894-37cf-4d02-859f-2ae0ccf762d3 | Status: 404 | Time: 0.001s
2025-03-02 20:46:40,554 - trakademik - INFO - Request started | 168b8cd8-4559-4906-8d75-ae3d25a35e70 | GET /docs
2025-03-02 20:46:40,555 - trakademik - INFO - Request completed | 168b8cd8-4559-4906-8d75-ae3d25a35e70 | Status: 200 | Time: 0.001s
2025-03-02 20:46:40,688 - trakademik - INFO - Request started | bf83c815-0d0a-4786-b92e-4ac5a4c9f281 | GET /openapi.json
2025-03-02 20:46:40,788 - trakademik - INFO - Request completed | bf83c815-0d0a-4786-b92e-4ac5a4c9f281 | Status: 200 | Time: 0.100s
2025-03-02 21:03:20,967 - trakademik - INFO - Application started
